name: DevOps CD Pipeline

"on":
  push:
    branches:
      - main

jobs:

  deployment:

    runs-on: self-hosted

    env:
      KUBECONFIG: C:\Users\Ranjith\.kube\config

    steps:

    # Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v4


    # Check Kubernetes connection
    - name: Check Kubernetes Context
      shell: powershell
      run: |
        kubectl config current-context
        kubectl get nodes


    # Deploy Backend
    - name: Deploy Backend
      shell: powershell
      run: |
        kubectl apply --validate=false -f k8s/backend-deployment.yml
        kubectl apply --validate=false -f k8s/backend-service.yml


    # Deploy Frontend
    - name: Deploy Frontend
      shell: powershell
      run: |
        kubectl apply --validate=false -f k8s/frontend-deployment.yml
        kubectl apply --validate=false -f k8s/frontend-service.yml


    # Deploy Blockchain
    - name: Deploy Blockchain
      shell: powershell
      run: |
        kubectl apply --validate=false -f k8s/blockchain-deployment.yaml
        kubectl apply --validate=false -f k8s/blockchain-service.yaml


    # Verify Deployment
    - name: Check Kubernetes Status
      shell: powershell
      run: |
        kubectl get pods
        kubectl get services